/**
 * Project VARI
 * @author Alexey Barashkov
 */

#ifndef _VDEFINITIONS_H
#define _VDEFINITIONS_H

#define ORGANIZATION_NAME   "${PROJECT_VENDOR_LONG}"
#define ORG_WEBSITE         "${ORG_WEBSITE}"
#define APPLICATION_NAME    "${APP_NAME}"
#define APPLICATION_VERSION "${PROJECT_VERSION_LONG}"

#define YEAR_STRING         "${CURRENT_YEAR}"
#define COMPILATION_TIME    "${CURRENT_TIME}"

#define PROJECT_VERSION_MAJOR   "${PROJECT_VERSION_MAJOR}"
#define PROJECT_VERSION_MINOR   "${PROJECT_VERSION_MINOR}"
#define PROJECT_VERSION_PATCH   "${PROJECT_VERSION_PATCH}"
#define PROJECT_VERSION_TWEAK   "${PROJECT_VERSION_TWEAK}"

#endif // _VDEFINITIONS_H
