typedef VMutexPtr std::shared_ptr<std::mutex>
typedef VSimulatorPtr std::shared_ptr<VSimulator>
typedef VGraphicsViewerPtr std::shared_ptr<VGraphicsViewer>
typedef VLayersProcessorPtr std::shared_ptr<VLayersProcessor>
typedef VTrianglePtr std::shared_ptr<VSimTriangle>
typedef VNodePtr std::shared_ptr<VSimNode>
typedef VSimElemPtr std::shared_ptr<VSimElement>
typedef VSimParamPtr std::shared_ptr<VSimulationParametres>
typedef VMaterialPtr std::shared_ptr<VMaterial>
typedef VLayerPtr std::shared_ptr<VLayer>
