#!/bin/bash
set -e

ldconfig

for USERDIR in /home/* ; do
  if test ! -d "$USERDIR/Desktop" ; then continue ; fi
  cp -f /usr/share/applications/vari.desktop "$USERDIR/Desktop"
  chmod 755 "$USERDIR/Desktop/vari.desktop"
  USER=$(basename $USERDIR)
  chown ${USER}:${USER} "$USERDIR/Desktop/vari.desktop"
done
exit 0
