#!/bin/bash
set -e

if [[ "$1" == "remove" || "$1" == "purge" ]]; then
	ldconfig
fi

for USER in /home/* ; do
  if test ! -f "$USER/Desktop/vari.desktop" ; then continue ; fi
  rm -f "$USER/Desktop/vari.desktop"
done
exit 0
